### ISSUE TITLE
How to use this example?

### ISSUE THREAD

**Issue by xcme** [fpiette/Logitech-Gaming-LED-SDK-for-Delphi#1]
Hi,

I tried to use your code but it didn't work for me. I'm looking for a way to get rid of LGS/G-HUB at all. 20 years ago I was familiar with Delphi, so I tried to run this example but got access violation related to "LogiLedGetSdkVersion". I see you mentioned:

> And you need the Logitech SDK DLL to be deployed which is easily done by installing "Logitech G HUB" application that is used to configure Logitech hardware.

I downloaded the SDK and put DLLs I found there to the .exe folder but it didn't help. Is it enough to have some DLL or G-HUB must be installed in the system?

**Comment by xcme** [comment]
What I exactly observe:
```
Your keyboard is pulsing for 5 seconds...
Exception Exception in module LogitechLedConsoleDemo.exe at 000000000016C9BC.
Entry point "LogiLedGetSdkVersion" not found.
```

**Comment by fpiette** [comment]
This error message means that the DLL is found but the entry point "LogiLedGetSdkVersion" does not exists in the DLL. This comes from an incorrect DLL, either corrupted or wrong version. On my system, the DLL is located at "C:\Program Files\LGHUB\sdk_legacy_led_x86.dll", it is version 9.2.65.0 and the file is date 09/03/2022 (Date of the last G-HUB self update).
Make sure you installed the latest G-HUB product or at least one dated after 09/12/2020 when I created the software.

**Comment by xcme** [comment]
Thanks for the hint. I installed LG HUB and when it's installed your example is working fine and leds are pulsing. But if I remove it, then app stops to work and throws out that error. Then I copied all DLLs to the app folder and without LG HUB installed and with these DLLs it doesn't show any error, shows this:
```
Your keyboard is pulsing for 5 seconds...
Hit RETURN
```
But does nothing and should be interrupted then by Ctrl+C. Is it possible to make it work without installed LG HUB? Both LGS and LG HUB are bloatware and I see no reason to use them. Having small console program would be better for me.

**Comment by fpiette** [comment]
You should probably NOT uninstall LG-HUB with normal uninstaller. Instead remove his files one by one, checking my sample between each file remove. When you deleted one file and my sample doesn't work anymore, then that file was required and undelete it.
It is also possible that the SDK needs registry keys that are removed when you uninstall LG-HUB, or reference DLL that you moved around.
All that is not a problem with my code but how LG-HUB is working. Since it is largely undocumented, you have to play with the thing to achieve your goal.
Using ProcessExplorer and ProcessMonitor will help you understanding what files and registry keys are used by the SDK.

**Comment by xcme** [comment]
I found "Logitech Gaming LED SDK" document and it says that LGS must be installed and run. Seems that's impossible to use that SDK in standalone applications. :(

**Comment by fpiette** [comment]
OK.
